----------------------------------------------------------------------------------------------------------------
-- CREATE menurole and grant to user
----------------------------------------------------------------------------------------------------------------
create role menurole;
GRANT menurole  TO propalladmin;


----------------------------------------------------------------------------------------------------------------
-- CREATE structure of menu
----------------------------------------------------------------------------------------------------------------
create table menu (
                        id number generated by default as identity primary key,
                        ismenu varchar2(1)not null check(ismenu = 'Y' or ismenu = 'N'),
                        hu_menuname varchar2(30) not null unique
                        --,en_menuname varchar2(30) not null unique
                        );
create view view_mainmenu as select * from menu;
create or replace synonym "mainmenu" for view_mainmenu;
GRANT select ON "mainmenu" TO menurole;

---------------
--Main menu list:
---------------
insert into "mainmenu" (ismenu, hu_menuname) values ('N', 'Törzsadatok');
insert into  "mainmenu"  (ismenu, hu_menuname) values ('N', 'Cikk törzsadatok');
insert into  "mainmenu"  (ismenu, hu_menuname) values ('N', 'Számla adatok');

select * from "mainmenu";
/
create table menu_1(
                        id number generated always as identity primary key,
                        ismenu varchar2(1) not null check(ismenu = 'Y' or ismenu = 'N'),
                        hu_menuname varchar2(30) not null unique,
                        parentmenu_fk number not null,
                        foreign key(parentmenu_fk) references menu(id)
                    );
create view view_menu_1 as select * from menu_1;
create or replace synonym "Törzsadatok" for view_menu_1;
GRANT select ON "Törzsadatok" TO menurole;

---------------
--Submenu list of menu_1:
---------------
insert into "Törzsadatok"(ismenu, hu_menuname, parentmenu_fk) values('N', 'Partner', 1);
insert into "Törzsadatok"(ismenu, hu_menuname, parentmenu_fk) values('N', 'Ország', 1);
insert into "Törzsadatok"(ismenu, hu_menuname, parentmenu_fk) values('N', 'Megye', 1);
insert into "Törzsadatok"(ismenu, hu_menuname, parentmenu_fk) values('N', 'Település', 1);
insert into "Törzsadatok"(ismenu, hu_menuname, parentmenu_fk) values('N', 'Közterület tipus', 1);
/
create table menu_2(
                        id number generated always as identity primary key,
                        ismenu varchar2(1) not null check(ismenu = 'Y' or ismenu = 'N'),
                        hu_menuname varchar2(30) not null unique,
                        parentmenu_fk number not null,
                        foreign key(parentmenu_fk) references menu(id)
                    );
create view view_menu_2 as select * from menu_2;
create or replace synonym "Cikk törzsadatok" for view_menu_2;
GRANT select ON "Cikk törzsadatok" TO menurole;

---------------
--Submenu list of menu_2:
---------------
insert into "Cikk törzsadatok"(ismenu, hu_menuname, parentmenu_fk) values('N', 'Teszt törzsadat', 1);
/
create table menu_3(
                        id number generated always as identity primary key,
                        ismenu varchar2(1) not null check(ismenu = 'Y' or ismenu = 'N'),
                        hu_menuname varchar2(30) not null unique,
                        parentmenu_fk number not null,
                        foreign key(parentmenu_fk) references menu(id)
                    );
create view view_menu_3 as select * from menu_3;
create or replace synonym "Számla adatok" for view_menu_3;
GRANT select ON "Számla adatok" TO menurole;

commit;
----------------------------------------------------------------------------------------------------------------
-- CREATE masterdataselectrole and grant to user
----------------------------------------------------------------------------------------------------------------
create role masterdataselectrole;
GRANT masterdataselectrole  TO propalladmin;

----------------------------------------------------------------------------------------------------------------
-- CREATE synonyms of view and insert of synonymname to cashtable
----------------------------------------------------------------------------------------------------------------
create or replace synonym "Partner" for HU_VIEW_BASICPARTNER;
GRANT select ON "Partner" TO masterdataselectrole;
insert into cashtable (cashtype_fk_id, synonymname) values (1, 'Partner');

create or replace synonym "Közterület tipus" for HU_VIEW_PUBLICPLACECATEGORY;
GRANT select ON "Közterület tipus" TO masterdataselectrole;
insert into cashtable (cashtype_fk_id, synonymname) values (1, 'Közterület tipus');

create or replace synonym "Ország" for HU_VIEW_COUNTRY;
GRANT select ON "Ország" TO masterdataselectrole;
insert into cashtable (cashtype_fk_id, synonymname) values (1, 'Ország');

create or replace synonym "Település" for HU_VIEW_SETTLEMENT;
GRANT select ON "Település" TO masterdataselectrole;
insert into cashtable (cashtype_fk_id, synonymname) values (1, 'Település');

create or replace synonym "Megye" for HU_VIEW_REGIONPLACE;
GRANT select ON "Megye" TO masterdataselectrole;
insert into cashtable (cashtype_fk_id, synonymname) values (1, 'Megye');

commit;

----------------------------------------------------------------------------------------------------------------
-- CREATE MENU FULL PROCEDURE (create synonyms of view, insert of synonymname to cashtable, insert name of synonyms of view to current menu
----------------------------------------------------------------------------------------------------------------
create or replace synonym "Magánszemély" for HU_VIEW_PERSONDATAv1;
insert into cashtable (cashtype_fk_id, synonymname) values (1, 'Magánszemély');
insert into "Törzsadatok"(ismenu, hu_menuname, parentmenu_fk) values('N', 'Magánszemély', 1);
commit;
