-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2020-05-10 21:12:54 CEST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



create table additionaldatatypeforinv (
    id            integer not null,
    name          varchar2(200) not null,
    description   varchar2(200) not null,
    value         varchar2(200)
);

alter table additionaldatatypeforinv add constraint additionaldatatypeforinv_pk primary key ( id );


alter table additionaldatatypeforinv add constraint addatatypeforinv_name_un unique ( name );

create table aircraft (
    id               integer not null,
    takeoffweight    number(22, 6) not null,
    aircargo         varchar2(5 char) not null,
    operationhours   number(22, 6) not null
);

alter table aircraft add constraint aircraft_pk primary key ( id );

create table bank (
    id     integer not null,
    name   varchar2(150) not null,
    iban   varchar2(4) not null
);

alter table bank add constraint bank_pk primary key ( id );

create table basicpartner (
    id                       integer not null,
    name                     varchar2(150) not null,
    puplicplacename          varchar2(50) not null,
    publicplacecategory_id   integer not null,
    "number"                 varchar2(12),
    building                 varchar2(12),
    staircase                varchar2(12),
    floorupstair             varchar2(12),
    door                     varchar2(12),
    lotnumber                varchar2(20),
    country_id               integer not null,
    settlement_id            integer not null,
    region_id                integer not null
);

alter table basicpartner add constraint basicpartner_pk primary key ( id );

create table concern (
    basicpartner_id           integer not null,
    individualexemption       varchar2(5 char) not null,
    exciselicencenum          varchar2(50),
    cashaccountingindicator   varchar2(5 char) not null,
    internalid                varchar2(6) not null
);

alter table concern add constraint concern_pk primary key ( basicpartner_id );

alter table concern add constraint concern_internalid_un unique ( internalid );

create table concernbankacnum (
    id                        integer not null,
    bankaccountnumber         varchar2(34 char) not null,
    bank_id                   integer not null,
    concernbankacnumtype_id   integer not null,
    concern_basicpartner_id   integer not null
);

alter table concernbankacnum add constraint concernbankacnum_pk primary key ( id );

create table concernbankacnumtype (
    id     integer not null,
    name   varchar2(30)
);

alter table concernbankacnumtype add constraint concernbankacnumtype_pk primary key ( id );

create table concernfiscalrepresentative (
    fiscalrepr_basicpartner_id   integer not null,
    concern_basicpartner_id      integer not null
);

alter table concernfiscalrepresentative add constraint concernfiscalrepresentative_pk primary key ( fiscalrepr_basicpartner_id,
                                                                                                    concern_basicpartner_id );

create table concerninvoiceblock (
    id                        varchar2(6) not null,
    code                      varchar2(6) not null,
    name                      varchar2(50),
    description               varchar2(150),
    concernbankacnum_id       integer not null,
    concern_basicpartner_id   integer not null
);

alter table concerninvoiceblock add constraint concerninvoiceblock_pk primary key ( id );



alter table concerninvoiceblock add constraint concerninv_basicpart_id_un unique ( code, concern_basicpartner_id );

create table contact (
    id                           integer not null,
    name                         varchar2(150) not null,
    contactcategory_id           integer not null,
    customer_basicpartner_id     integer not null,
    fiscalrepr_basicpartner_id   integer not null
);

alter table contact add constraint contact_pk primary key ( id );

create table contactcategory (
    id     integer not null,
    name   varchar2(50)
);

alter table contactcategory add constraint contactcategory_pk primary key ( id );

create table contactdata (
    id                       integer not null,
    puplicplacename          varchar2(50),
    "number"                 varchar2(12),
    building                 varchar2(12),
    staircase                varchar2(12),
    floorupstair             varchar2(12),
    door                     varchar2(12),
    lotnumber                varchar2(20),
    phonenumber              number(16, 4),
    "e-mail"                 varchar2(50),
    contact_id               integer not null,
    country_id               integer not null,
    settlement_id            integer not null,
    region_id                integer not null,
    publicplacecategory_id   integer not null
);

alter table contactdata add constraint contactdata_pk primary key ( id,
                                                                    publicplacecategory_id );

create table country (
    id            integer not null,
    countrycode   varchar2(2 char) not null,
    name          varchar2(50) not null
);

alter table country add constraint country_pk primary key ( id );

create table currency (
    id             integer not null,
    name           varchar2(50) not null,
    currencycode   varchar2(3 char) not null,
    value          number(16, 4)
);

alter table currency add constraint currency_pk primary key ( id );

alter table currency add constraint currency_currencycode_un unique ( currencycode );

create table customer (
    basicpartner_id        integer not null,
    thirdstatetaxid        varchar2(20),
    taxpayertype_id        integer not null,
    selfbillingindicator   varchar2(5 char) not null
);

alter table customer add constraint customer_pk primary key ( basicpartner_id );

create table customerbankacnum (
    id                         integer not null,
    bankaccountnumber          varchar2(34 char) not null,
    bank_id                    integer not null,
    customer_basicpartner_id   integer not null
);

alter table customerbankacnum add constraint customerbankacnum_pk primary key ( id );

create table customerdeclaration (
    id                 integer not null,
    productweight      number(22, 6),
    productstream_id   integer not null
);

alter table customerdeclaration add constraint customerdeclaration_pk primary key ( id );

create table dieseloilpurchase (
    itemline_id                 integer not null,
    basicpartner_id             integer not null,
    purchasedate                date not null,
    vehicleregistrationnumber   varchar2(30),
    dieseloilquantity           number(22, 6)
);

alter table dieseloilpurchase add constraint dieseloilpurchase_pk primary key ( itemline_id );

create table enterprisedata (
    basicpartner_id        integer not null,
    groupmembertaxnumber   varchar2(20),
    communityvatnumber     varchar2(20)
);

alter table enterprisedata add constraint enterprisedata_pk primary key ( basicpartner_id );

create table exchangerate (
    id                        integer not null,
    value                     number(14, 6) not null,
    fromdate                  date not null,
    todate                    date,
    currency_id               integer not null,
    exchangeratecategory_id   integer not null
);

alter table exchangerate add constraint exchangerate_pk primary key ( id );


alter table exchangerate add constraint exchanger_currency_id_un unique ( fromdate,
                                                                                      currency_id );

create table exchangeratecategory (
    id     integer not null,
    name   varchar2(50) not null
);

alter table exchangeratecategory add constraint exchangeratecategory_pk primary key ( id );

alter table exchangeratecategory add constraint exchangeratecategory_name_un unique ( name );

create table fiscalrepbankacnum (
    id                           integer not null,
    bankaccountnumber            varchar2(34 char) not null,
    bank_id                      integer not null,
    fiscalrepr_basicpartner_id   integer not null
);

alter table fiscalrepbankacnum add constraint fiscalrepbankacnum_pk primary key ( id );

create table fiscalrepresentative (
    basicpartner_id integer not null
);

alter table fiscalrepresentative add constraint fiscalrepresentative_pk primary key ( basicpartner_id );

create table internaltaxnumber (
    basicpartner_id   integer not null,
    taxpayerid        number(8) not null,
    vatcode           number(1) not null,
    countycode        number(2)
);

alter table internaltaxnumber add constraint internaltaxnumber_pk primary key ( basicpartner_id );


alter table internaltaxnumber add constraint internaltaxnum_taxpayerid_un unique ( taxpayerid );

create table invoice (
    id                              integer not null,
    paymentmethod_id                integer not null,
    invoicecategory_id_fk           integer not null,
    invoiceappearance_id            integer not null,
    currency_id                     integer not null,
    concerninvoiceblock_id          varchar2(6) not null,
    additionaldatatypeforinv_id     integer not null,
    adddatatypeforinvdataname       varchar2(200),
    adddatatypeforinvdatadescr      varchar2(200),
    adddatatypeforinvdatavalue      varchar2(200),
    invoicenumber                   varchar2(30) not null,
    invoicecategory                 varchar2(12) not null,
    invoiceissuedate                date not null,
    invoicedeliverydate             date not null,
    invoicedeliveryperiodstart      date,
    invoicedeliveryperiodend        date,
    invoiceaccountingdeliverydate   date not null,
    currencycode                    varchar2(4) not null,
    exchangerate                    number(14, 6) not null,
    selfbillingindicator1           varchar2(5 char),
    paymentmethod                   varchar2(50),
    paymentdate                     date not null,
    cashaccountingindicator         varchar2(5 char) not null,
    invoiceappearance               varchar2(10),
    electronicinvoicehash           varchar2(64),
    originalinvoicenumber           varchar2(30),
    modificationissuedate           date,
    modificationtimestamp           timestamp,
    lastmodificationreference       varchar2(30),
    modifywithoutmaster             varchar2(5 char),
    suppliertaxpayerid              number(8) not null,
    suppliervatcode                 number(1) not null,
    suppliercounrtycodetax          varchar2(2) not null,
    suppliergroupmembertaxnumber    varchar2(20),
    suppliercommunityvatnumber      varchar2(20),
    suppliername                    varchar2(150) not null,
    suppliercountrycode             varchar2(2 char) not null,
    suppliercountry                 varchar2(50) not null,
    supplierregion                  varchar2(2 char),
    supplierpostalcode              varchar2(10) not null,
    suppliersettlement              varchar2(50) not null,
    supplierpublicplacename         varchar2(50) not null,
    supplierpublicplacecategory     varchar2(50) not null,
    suppliernumber                  varchar2(12),
    supplierbuilding                varchar2(12),
    supplierstaircase               varchar2(12),
    supplierfloorupstair            varchar2(12),
    supplierdoor                    varchar2(12),
    supplierlotnumber               varchar2(20),
    supplierbankaccountnumber       varchar2(34 char) not null,
    individualexemption             varchar2(5 char) not null,
    exciselicencenum                varchar2(50),
    customername                    varchar2(150) not null,
    customertaxpayerid              number(8) not null,
    customervatcode                 number(1) not null,
    customercountrycodetax          varchar2(2) not null,
    customergroupmembertaxnumber    varchar2(20),
    customercommunityvatnumber      varchar2(20),
    thirdstatetaxid                 varchar2(20),
    customercountrycode             varchar2(2 char) not null,
    customercountry                 varchar2(50) not null,
    customerregion                  varchar2(2 char),
    customerpostalcode              varchar2(10) not null,
    customersettlement              varchar2(50) not null,
    customerpublicplacename         varchar2(50) not null,
    customerpublicplacecategory     varchar2(50) not null,
    customernumber                  varchar2(12),
    customerbuilding                varchar2(12),
    customerstaircase               varchar2(12),
    customerfloorupstair            varchar2(12),
    customerdoor                    varchar2(12),
    customerlotnumber               varchar2(20),
    customerbankaccountnumber       varchar2(34 char) not null,
    fiscalreprtaxpayerid            number(8) not null,
    fiscalrepresentativevatcode     number(1) not null,
    fiscalreprcountrycodevat        varchar2(2) not null,
    fiscalrepresentativename        varchar2(150),
    fiscalreprcountrycode           varchar2(2 char) not null,
    fiscalreprcountry               varchar2(50) not null,
    fiscalreprregion                varchar2(2 char),
    fiscalreprpostalcode            varchar2(10) not null,
    fiscalreprsettlement            varchar2(50) not null,
    fiscalreprpublicplacename       varchar2(50) not null,
    fiscalreprpublicplacecategory   varchar2(50) not null,
    fiscalreprnumber                varchar2(12),
    fiscalreprbuilding              varchar2(12),
    fiscalreprstaircase             varchar2(12),
    fiscalreprfloorupstair          varchar2(12),
    fiscalreprdoor                  varchar2(12),
    fiscalreprlotnumber             varchar2(20),
    fiscalreprbankaccountnumber     varchar2(34 char) not null,
    invoicenetamount                number(18, 2) not null,
    invoicevatamount                number(18, 2) not null,
    invoicevatamounthuf             number(18, 2) not null,
    productfeeoperation             varchar2(7 char),
    productchargesum                number(18, 2),
    evidencedocumentno              varchar2(50) not null,
    evidencedocumentdate            date not null,
    obligatedname                   varchar2(150),
    obligatedcountrycode            varchar2(2 char) not null,
    obligatedregion                 varchar2(2 char),
    obligatedpostalcode             varchar2(10) not null,
    obligatedsettlement             varchar2(50) not null,
    obligatedpublicplacename        varchar2(50) not null,
    obligatedpublicplacecategory    varchar2(50) not null,
    obligatednumber                 varchar2(12),
    obligatedbuilding               varchar2(12),
    obligatedstaircase              varchar2(12),
    obligatedfloorupstair           varchar2(12),
    obligateddoor                   varchar2(12),
    obligatedlotnumber              varchar2(20),
    obligatedtaxpayerid             number(8) not null,
    obligatedvatcode                number(1) not null,
    obligatedcountycode             number(2),
    productfeecontentfeeamount      number(18, 2),
    productfeecontentfeecode        varchar2(5 char),
    productfeecontentfeequant       number(22, 6),
    productfeecontentfeerate        number(18, 2),
    productfeeconttfeemeasunit      varchar2(6),
    concern_basicpartner_id         integer not null,
    customer_basicpartner_id        integer not null
);

alter table invoice add constraint invoice_pk primary key ( id );

create table invoiceappearance (
    id     integer not null,
    name   varchar2(10)
);

alter table invoiceappearance add constraint invoiceappearance_pk primary key ( id );

create table invoicecategory (
    id     integer not null,
    name   varchar2(12)
);

create table invoicereferencetype (
    invoice_id                  integer not null,
    originalinvoicenumber       varchar2(30) not null,
    modificationissuedate       date not null,
    modificationtimestamp       timestamp not null,
    lastmodificationreference   varchar2(30),
    modifywithoutmaster         varchar2(5 char) not null
);

alter table invoicereferencetype add constraint invoicereferencetype_pk primary key ( invoice_id );

create table item (
    id                         integer not null,
    name                       varchar2(150) not null,
    ekaerids                   varchar2(20),
    additionallinedata         varchar2(100),
    productcodeownvalue        varchar2(30),
    marginschemeindicator_id   integer not null,
    productcode_id             integer not null,
    vat_id                     integer not null,
    unit_id                    integer not null
);

alter table item add constraint item_pk primary key ( id );

create table itembasicprice (
    id            integer not null,
    value         number(16, 4),
    item_id       integer not null,
    currency_id   integer not null
);

alter table itembasicprice add constraint itembasicprice_pk primary key ( id );

create table itemdiscount (
    id              integer not null,
    name            varchar2(150) not null,
    fromdate        date,
    todate          date,
    discountrate    number(5, 4),
    discountvalue   number(18, 2) not null,
    item_id         integer not null
);

alter table itemdiscount add constraint itemdiscount_pk primary key ( id );


alter table itemdiscount add constraint itemdisc_fromdate_item_id_un unique ( fromdate,
                                                                                  item_id );

create table itemline (
    id                               integer not null,
    linenumber                       integer not null,
    referencestootherlines           integer,
    advanceindicator                 varchar2(5 char) not null,
    productcodecategory              varchar2(5 char),
    productcodevalue                 varchar2(30),
    lineexpressionindicator          varchar2(5 char),
    linedescription                  varchar2(150) not null,
    quantity                         number(22, 6) not null,
    unitofmeasure                    varchar2(16) not null,
    unitofmeasureown                 varchar2(16),
    unitprice                        number(16, 4) not null,
    linediscountdataname             varchar2(150),
    linediscountdatadiscountrate     number(5, 4),
    linediscountdatadiscountvalue    number(18, 2),
    intermediatedservice             varchar2(5 char) not null,
    aggreginvlinedatalineexchrate    number(14, 6),
    aggreginvlinedatlinedelivdate    date,
    depositindicator                 varchar2(5 char) not null,
    marginschemeindicator            varchar2(16),
    ekaerids                         varchar2(20),
    obligatedforproductfee           varchar2(5 char) not null,
    gpcexcise                        number(18, 2),
    netadeclaration                  varchar2(5 char) not null,
    productfeeclausetakeoveram       number(18, 2),
    productfeeclausetakeoverreason   varchar2(5 char),
    productfeeclauseproductweight    number(22, 6),
    productfeeclauseproductstream    varchar2(150),
    additionallinedata               varchar2(200),
    dieseloilpurchasedate            date,
    dieseloilpurchvehicleregnumber   varchar2(30),
    dieseloilpurchasequantity        number(22, 6),
    dieselpurchasecountrycode        varchar2(2),
    dieselpurchasecountryname        varchar2(50),
    dieselpurchasesettlementname     varchar2(50),
    dieselpurchasepostalcode         integer,
    dieselpurchasepublicplacename    varchar2(50),
    dieselpurchasepublicplacecateg   varchar2(50),
    dieselpurchasenumber             varchar2(12),
    dieselpurchasebuilding           varchar2(12),
    dieselpurchasestaircase          varchar2(12),
    dieselpurchasefloorupstair       varchar2(12),
    dieselpurchasedoor               varchar2(12),
    dieselpurchaselotnumber          varchar2(20),
    lineproductfeecontentfeecode     varchar2(5 char),
    lineproductfeeconttfeemeasunit   varchar2(6),
    lineproductfeecontentfeerate     number(18, 2),
    lineproductfeecontentfeeamount   number(18, 2),
    lineproductfeecontentfeequant    number(22, 6),
    newtransportmeanbrand            varchar2(100),
    newtransportmeanserialnum        varchar2(100),
    newtransportmeanenginenum        varchar2(100),
    newtransportmeanfirstentinserv   date,
    newtransportmeanenginecapacity   number(22, 6),
    newtransportmeanenginepower      number(22, 6),
    newtransportmeankms              number(22, 6),
    newtransportmeanlength           number(22, 6),
    newtransportmeanactivityref      varchar2(5 char),
    newtransportmeansailedhours      number(22, 6),
    newtransportmeantakeoffweight    number(22, 6),
    newtransportmeanaircargo         varchar2(5 char),
    newtransportmeanoperationhours   number(22, 6),
    linemodificationreferencename    varchar2(6),
    linemodificationreflinenumref    integer,
    linenetamount                    number(18, 2) not null,
    linevatamount                    number(18, 2) not null,
    linevatamounthuf                 number(18, 2) not null,
    linegrossamountnormal            number(18, 2) not null,
    linevatratename                  varchar2(50) not null,
    linevatratevatpercentage         number(5, 4),
    linevatratevatexemption          varchar2(100),
    linevatratevatdomestrevcharge    varchar2(5 char),
    linevatratevatmarginschemevat    varchar2(5 char),
    linevatratemarginschemenovat     varchar2(5 char),
    linevatratevatoutofscope         varchar2(5 char),
    currencycode                     varchar2(3 char) not null,
    lineoperation_id                 integer not null,
    item_id                          integer not null,
    invoice_id                       integer not null
);

alter table itemline add constraint itemline_pk primary key ( id );


create table itemproperty (
    item_id                   integer not null,
    lineexpressionindicator   varchar2(5 char) not null,
    depositindicator          varchar2(5 char) not null,
    obligatedforproductfee    varchar2(5 char) not null,
    netadeclaration           varchar2(5 char) not null,
    intermediatedservice1     varchar2(5 char) not null,
    gpcexcise                 number(18, 2)
);

alter table itemproperty add constraint itemproperty_pk primary key ( item_id );

alter table itemproperty add constraint itemproperty_item_id_un unique ( item_id );

create table lineoperation (
    id     integer not null,
    name   varchar2(6)
);

alter table lineoperation add constraint lineoperation_pk primary key ( id );

create table lineproductfeeclausecontent (
    itemproperty_item_id      integer not null,
    productfeecode            varchar2(5 char),
    productfeemeasuringunit   varchar2(6),
    productfeerate            number(18, 2),
    productfeeamount          number(18, 2),
    productfeequantity        number(22, 6)
);

create unique index lineproductfeeclausecont_idx on
    lineproductfeeclausecontent (
        itemproperty_item_id
    asc );

alter table lineproductfeeclausecontent add constraint lineprodfeeclausecont_un unique ( itemproperty_item_id );

create table marginschemeindicator (
    id     integer not null,
    name   varchar2(16) not null
);

alter table marginschemeindicator add constraint marginschemeindicator_pk primary key ( id );

alter table marginschemeindicator add constraint marginschemeindicator_name_un unique ( name );

create table navuser (
    concern_basicpartner_id   integer not null,
    login                     varchar2(15 char) not null,
    passwordhash              varchar2(128) not null,
    taxnumber                 number(8),
    requestsignature          varchar2(128)
);

alter table navuser add constraint navuser_pk primary key ( concern_basicpartner_id );

alter table navuser add constraint navuser_login_un unique ( login );

create table paymentmethod (
    id     integer not null,
    name   varchar2(50) not null
);

alter table paymentmethod add constraint paymentmethod_pk primary key ( id );

alter table paymentmethod add constraint paymentmethod_name_un unique ( name );

create table persondata (
    basicpartner_id   integer not null,
    birthday          date,
    nameofmothers     varchar2(150),
    country_id        integer not null,
    region_id         integer not null,
    settlement_id     integer not null
);

alter table persondata add constraint persondata_pk primary key ( basicpartner_id );

create table productcode (
    id                       integer not null,
    productcodevalue         varchar2(30) not null,
    productcodecategory_id   integer not null
);

alter table productcode add constraint productcode_pk primary key ( id );

create table productcodecategory (
    id     integer not null,
    name   varchar2(5 char)
);

alter table productcodecategory add constraint productcodecategory_pk primary key ( id );

create table productfeeclause (
    itemline_id              integer not null,
    takeoverreason_id        integer not null,
    takeoveramount           number(18, 2),
    customerdeclaration_id   integer not null
);

alter table productfeeclause add constraint productfeeclause_pk primary key ( itemline_id );

create table productstream (
    id     integer not null,
    name   varchar2(150) not null
);

alter table productstream add constraint productstream_pk primary key ( id );

alter table productstream add constraint productstream_name_un unique ( name );

create table publicplacecategory (
    id     integer not null,
    name   varchar2(50) not null
);

alter table publicplacecategory add constraint publicplacecategory_pk primary key ( id );

create table regionplace (
    id           integer not null,
    name         varchar2(50) not null,
    regioncode   varchar2(2 char),
    country_id   integer not null
);

alter table regionplace add constraint region_pk primary key ( id );

create table settlement (
    id           integer not null,
    name         varchar2(50) not null,
    country_id   integer not null,
    postalcode   varchar2(12)
);

alter table settlement add constraint settlement_pk primary key ( id );

create table summarybyvatrate (
    id                         integer not null,
    vatratenetamount           number(18, 2) not null,
    vatratevatamount           number(18, 2) not null,
    vatratevatamounthuf        number(18, 2),
    vatrategrossamount         number(18, 2),
    vatpercentage              number(5, 4),
    vatexemption               varchar2(100),
    vatdomesticreversecharge   varchar2(5 char) not null,
    marginschemevat            varchar2(5 char) not null,
    marginschemenovat          varchar2(5 char) not null,
    vatoutofscope              varchar2(5 char) not null,
    vat_id                     integer not null,
    invoice_id                 integer not null
);

alter table summarybyvatrate add constraint summarybyvatrate_pk primary key ( id );

create table takeoverreason (
    id     integer not null,
    name   varchar2(5 char) not null
);

alter table takeoverreason add constraint takeoverreason_pk primary key ( id );

alter table takeoverreason add constraint takeoverreason_name_un unique ( name );

create table taxpayertype (
    id            integer not null,
    name          varchar2(50) not null,
    description   varchar2(200)
);

alter table taxpayertype add constraint taxpayertype_pk primary key ( id );

create table taxproperty (
    vatpercentage              number(5, 4),
    vatexemption               varchar2(100),
    vatdomesticreversecharge   varchar2(5 char) not null,
    marginschemevat            varchar2(5 char) not null,
    marginschemenovat          varchar2(5 char) not null,
    vatoutofscope              varchar2(5 char) not null,
    vat_id                     integer not null
);

create unique index taxproperty__idx on
    taxproperty (
        vat_id
    asc );

create table transportmeans (
    item_id                 integer not null,
    brand                   varchar2(100),
    serialnum               varchar2(100),
    enginenum               varchar2(100),
    firstentryintoservice   date not null,
    transportmeanstype_id   integer not null
);

alter table transportmeans add constraint transportmeans_pk primary key ( item_id );

create table transportmeanstype (
    id            integer not null,
    name          varchar2(50),
    vehicle_id    integer,
    vessel_id     integer,
    aircraft_id   integer
);

alter table transportmeanstype
    add constraint arc_7 check ( ( ( vehicle_id is not null )
                                   and ( vessel_id is null )
                                   and ( aircraft_id is null ) )
                                 or ( ( vessel_id is not null )
                                      and ( vehicle_id is null )
                                      and ( aircraft_id is null ) )
                                 or ( ( aircraft_id is not null )
                                      and ( vehicle_id is null )
                                      and ( vessel_id is null ) ) );

create unique index transportmeanstype__idx on
    transportmeanstype (
        aircraft_id
    asc );

create unique index transportmeanstype__idxv1 on
    transportmeanstype (
        vehicle_id
    asc );

create unique index transportmeanstype__idxv2 on
    transportmeanstype (
        vessel_id
    asc );

alter table transportmeanstype add constraint transportmeanstype_pk primary key ( id );

create table unit (
    id                 integer not null,
    name               varchar2(16) not null,
    unitofmeasure      varchar2(16),
    unitofmeasurehun   varchar2(16) 
);

alter table unit add constraint unit_pk primary key ( id );

alter table unit add constraint unit_name_un unique ( name );

alter table unit add constraint unit_unitofmeasure_un unique ( unitofmeasure );

create table vat (
    id            integer not null,
    name          varchar2(50) not null,
    description   varchar2(50) not null
);

alter table vat add constraint vat_pk primary key ( id );

alter table vat add constraint vat_name_un unique ( name );

create table vehicle (
    id               integer not null,
    enginecapacity   number(22, 6) not null,
    enginepower      number(22, 6) not null,
    kms              number(22, 6) not null
);

alter table vehicle add constraint vehicle_pk primary key ( id );

create table vessel (
    id                 integer not null,
    length             number(22, 6) not null,
    activityreferred   varchar2(5 char) not null,
    sailedhours        number(22, 6) not null
);

alter table vessel add constraint vessel_pk primary key ( id );

alter table basicpartner
    add constraint basicpartner_country_fk foreign key ( country_id )
        references country ( id );

alter table basicpartner
    add constraint basicp_publicplacecat_fk foreign key ( publicplacecategory_id )
        references publicplacecategory ( id );

alter table basicpartner
    add constraint basicpartner_region_fk foreign key ( region_id )
        references regionplace ( id );

alter table basicpartner
    add constraint basicpartner_settlement_fk foreign key ( settlement_id )
        references settlement ( id );

alter table concern
    add constraint concern_basicpartner_fk foreign key ( basicpartner_id )
        references basicpartner ( id );

alter table concernbankacnum
    add constraint concernbankacnum_bank_fk foreign key ( bank_id )
        references bank ( id );

alter table concernbankacnum
    add constraint concernbankacnum_concern_fk foreign key ( concern_basicpartner_id )
        references concern ( basicpartner_id );

alter table concernbankacnum
    add constraint conbankacnum_conbankacnum_fk foreign key ( concernbankacnumtype_id )
        references concernbankacnumtype ( id );

alter table concernfiscalrepresentative
    add constraint concernfiscalrepr_concern_fk foreign key ( concern_basicpartner_id )
        references concern ( basicpartner_id );

alter table concernfiscalrepresentative
    add constraint concernfiscrep_fisrepr_fk foreign key ( fiscalrepr_basicpartner_id )
        references fiscalrepresentative ( basicpartner_id );

alter table concerninvoiceblock
    add constraint concerninvoiceblock_concern_fk foreign key ( concern_basicpartner_id )
        references concern ( basicpartner_id );

alter table concerninvoiceblock
    add constraint concinvblock_concbacnum_fk foreign key ( concernbankacnum_id )
        references concernbankacnum ( id );

alter table contact
    add constraint contact_contactcategory_fk foreign key ( contactcategory_id )
        references contactcategory ( id );

alter table contact
    add constraint contact_customer_fk foreign key ( customer_basicpartner_id )
        references customer ( basicpartner_id );

alter table contact
    add constraint contact_fiscalrep_fk foreign key ( fiscalrepr_basicpartner_id )
        references fiscalrepresentative ( basicpartner_id );

alter table contactdata
    add constraint contactdata_contact_fk foreign key ( contact_id )
        references contact ( id );

alter table contactdata
    add constraint contactdata_country_fk foreign key ( country_id )
        references country ( id );

alter table contactdata
    add constraint contactd_publicplacecat_fk foreign key ( publicplacecategory_id )
        references publicplacecategory ( id );

alter table contactdata
    add constraint contactdata_region_fk foreign key ( region_id )
        references regionplace ( id );

alter table contactdata
    add constraint contactdata_settlement_fk foreign key ( settlement_id )
        references settlement ( id );

alter table customer
    add constraint customer_basicpartner_fk foreign key ( basicpartner_id )
        references basicpartner ( id );

alter table customer
    add constraint customer_taxpayertype_fk foreign key ( taxpayertype_id )
        references taxpayertype ( id );

alter table customerbankacnum
    add constraint customerbankacnum_bank_fk foreign key ( bank_id )
        references bank ( id );

alter table customerbankacnum
    add constraint customerbankacnum_customer_fk foreign key ( customer_basicpartner_id )
        references customer ( basicpartner_id );

alter table customerdeclaration
    add constraint customerdecl_productstr_fk foreign key ( productstream_id )
        references productstream ( id );

alter table dieseloilpurchase
    add constraint dieseloilpurch_basicp_fk foreign key ( basicpartner_id )
        references basicpartner ( id );

alter table dieseloilpurchase
    add constraint dieseloilpurchase_itemline_fk foreign key ( itemline_id )
        references itemline ( id );

alter table enterprisedata
    add constraint enterprisedata_basicpartner_fk foreign key ( basicpartner_id )
        references basicpartner ( id );

alter table exchangerate
    add constraint exchangerate_currency_fk foreign key ( currency_id )
        references currency ( id );
 
alter table exchangerate
    add constraint exchanger_exchangeratecat_fk foreign key ( exchangeratecategory_id )
        references exchangeratecategory ( id );

alter table fiscalrepbankacnum
    add constraint fiscalrepbankacnum_bank_fk foreign key ( bank_id )
        references bank ( id );

alter table fiscalrepbankacnum
    add constraint fiscalrep_fiscalrep_fk foreign key ( fiscalrepr_basicpartner_id )
        references fiscalrepresentative ( basicpartner_id );

alter table fiscalrepresentative
    add constraint fiscalrepr_basicpartner_fk foreign key ( basicpartner_id )
        references basicpartner ( id );

alter table internaltaxnumber
    add constraint internaltaxn_basicpartner_fk foreign key ( basicpartner_id )
        references basicpartner ( id );

alter table invoice
    add constraint invoice_additdatatypeinv_fk foreign key ( additionaldatatypeforinv_id )
        references additionaldatatypeforinv ( id );

alter table invoice
    add constraint invoice_concern_fk foreign key ( concern_basicpartner_id )
        references concern ( basicpartner_id );

alter table invoice
    add constraint invoice_concerninvoiceblock_fk foreign key ( concerninvoiceblock_id )
        references concerninvoiceblock ( id );

alter table invoice
    add constraint invoice_currency_fk foreign key ( currency_id )
        references currency ( id );

alter table invoice
    add constraint invoice_customer_fk foreign key ( customer_basicpartner_id )
        references customer ( basicpartner_id );

alter table invoice
    add constraint invoice_invoiceappearance_fk foreign key ( invoiceappearance_id )
        references invoiceappearance ( id );

alter table invoice
    add constraint invoice_paymentmethod_fk foreign key ( paymentmethod_id )
        references paymentmethod ( id );

alter table invoicereferencetype
    add constraint invoicereftype_invoice_fk foreign key ( invoice_id )
        references invoice ( id );

alter table item
    add constraint item_marginschemeindicator_fk foreign key ( marginschemeindicator_id )
        references marginschemeindicator ( id );

alter table item
    add constraint item_productcode_fk foreign key ( productcode_id )
        references productcode ( id );

alter table item
    add constraint item_unit_fk foreign key ( unit_id )
        references unit ( id );

alter table item
    add constraint item_vat_fk foreign key ( vat_id )
        references vat ( id );

alter table itembasicprice
    add constraint itembasicprice_currency_fk foreign key ( currency_id )
        references currency ( id );

alter table itembasicprice
    add constraint itembasicprice_item_fk foreign key ( item_id )
        references item ( id );

alter table itemdiscount
    add constraint itemdiscount_item_fk foreign key ( item_id )
        references item ( id );

alter table itemline
    add constraint itemline_invoice_fk foreign key ( invoice_id )
        references invoice ( id );

alter table itemline
    add constraint itemline_item_fk foreign key ( item_id )
        references item ( id );

alter table itemline
    add constraint itemline_lineoperation_fk foreign key ( lineoperation_id )
        references lineoperation ( id );

alter table itemproperty
    add constraint itemproperty_item_fk foreign key ( item_id )
        references item ( id );

alter table lineproductfeeclausecontent
    add constraint lineproductfeec_itemprop_fk foreign key ( itemproperty_item_id )
        references itemproperty ( item_id );

alter table navuser
    add constraint navuser_concern_fk foreign key ( concern_basicpartner_id )
        references concern ( basicpartner_id );

alter table persondata
    add constraint persondata_basicpartner_fk foreign key ( basicpartner_id )
        references basicpartner ( id );

alter table persondata
    add constraint persondata_country_fk foreign key ( country_id )
        references country ( id );

alter table persondata
    add constraint persondata_region_fk foreign key ( region_id )
        references regionplace ( id );

alter table persondata
    add constraint persondata_settlement_fk foreign key ( settlement_id )
        references settlement ( id );

alter table productcode
    add constraint productc_productcodecat_fk foreign key ( productcodecategory_id )
        references productcodecategory ( id );

alter table productfeeclause
    add constraint productfeec_customerdecl_fk foreign key ( customerdeclaration_id )
        references customerdeclaration ( id );

alter table productfeeclause
    add constraint productfeeclause_itemline_fk foreign key ( itemline_id )
        references itemline ( id );

alter table productfeeclause
    add constraint productfeec_takeover_fk foreign key ( takeoverreason_id )
        references takeoverreason ( id );

alter table regionplace
    add constraint region_country_fk foreign key ( country_id )
        references country ( id );

alter table settlement
    add constraint settlement_country_fk foreign key ( country_id )
        references country ( id );

alter table summarybyvatrate
    add constraint summarybyvatrate_invoice_fk foreign key ( invoice_id )
        references invoice ( id );

alter table summarybyvatrate
    add constraint summarybyvatrate_vat_fk foreign key ( vat_id )
        references vat ( id );

alter table taxproperty
    add constraint taxproperty_vat_fk foreign key ( vat_id )
        references vat ( id );

alter table transportmeans
    add constraint transportmeans_item_fk foreign key ( item_id )
        references item ( id );

alter table transportmeans
    add constraint transportm_transportmtype_fk foreign key ( transportmeanstype_id )
        references transportmeanstype ( id );

alter table transportmeanstype
    add constraint transportmeanstype_aircraft_fk foreign key ( aircraft_id )
        references aircraft ( id );

alter table transportmeanstype
    add constraint transportmeanstype_vehicle_fk foreign key ( vehicle_id )
        references vehicle ( id );

alter table transportmeanstype
    add constraint transportmeanstype_vessel_fk foreign key ( vessel_id )
        references vessel ( id );

CREATE OR REPLACE VIEW HU_VIEW_BANK ( id, "Bank név", iban ) AS
select
    bank.id     as id,
    bank.name   as "Bank név",
    bank.iban   as "iban"
from
    bank 
;

CREATE OR REPLACE VIEW HU_VIEW_BASICPARTNER ( id, Partnernév, "Közterület neve", "Közterület tipus ID", Házszám, Épület, Lépcsõház, Emelet, Ajtó, "Helyrajzi szám", "Ország ID", "Település ID", "Megye ID" ) AS
select
    basicpartner.id                       as id,
    basicpartner.name                     as "Partnernév",
    basicpartner.puplicplacename          as "Közterület neve",
    basicpartner.publicplacecategory_id   as "Közterület tipus ID",
    basicpartner."number"                 as "Házszám",
    basicpartner.building                 as "Épület",
    basicpartner.staircase                as "Lépcsõház",
    basicpartner.floorupstair             as "Emelet",
    basicpartner.door                     as "Ajtó",
    basicpartner.lotnumber                as "Helyrajzi szám",
    basicpartner.country_id               as "Ország ID",
    basicpartner.settlement_id            as "Település ID",
    basicpartner.region_id                as "Megye ID"
from
    basicpartner 
;

CREATE OR REPLACE VIEW HU_VIEW_CONCERBANKACNUMTYPE ( id, "Bankszámla tipus" ) AS
select
    concernbankacnumtype.id     as id,
    concernbankacnumtype.name   as "Bankszámla tipus"
from
    concernbankacnumtype 
;

CREATE OR REPLACE VIEW HU_VIEW_CONCERNBANKACNUM ( id, Bankszámlaszám, "Bank ID", "Bankszámla típus ID", "Számlakibocsátó ID" ) AS
select
    concernbankacnum.id                        as id,
    concernbankacnum.bankaccountnumber         as "Bankszámlaszám",
    concernbankacnum.bank_id                   as "Bank ID",
    concernbankacnum.concernbankacnumtype_id   as "Bankszámla típus ID",
    concernbankacnum.concern_id                as "Számlakibocsátó ID"
from
    concernbankacnum 
;

CREATE OR REPLACE VIEW HU_VIEW_CONCERNINNVOICEBLOCK ( id, "Számlatömb kód", "Számlatömb név", "Számlatömb leírás", "Bankszámla ID", "Számlakiállító ID" ) AS
select
    concerninvoiceblock.id                        as id,
    concerninvoiceblock.code                      as "Számlatömb kód",
    concerninvoiceblock.name                      as "Számlatömb név",
    concerninvoiceblock.description               as "Számlatömb leírás",
    concerninvoiceblock.concernbankacnum_id       as "Bankszámla ID",
    concerninvoiceblock.concern_basicpartner_id   as "Számlakiállító ID"
from
    concerninvoiceblock 
;

CREATE OR REPLACE VIEW HU_VIEW_CONCERNv1 ( id, "Alanyi ÁFA mentes", "Adóraktári/jövedéki engedély szám", "Pénzforgalmi elszámolás", Önadózó ) AS
select
    concern.basicpartner_id           as id,
    concern.individualexemption       as "Alanyi ÁFA mentes",
    concern.exciselicencenum          as "Adóraktári/jövedéki engedély szám",
    concern.cashaccountingindicator   as "Pénzforgalmi elszámolás",
    concern.internalid                as "Önadózó"
from
    concern 
;

CREATE OR REPLACE VIEW HU_VIEW_CONTACT ( id, "Kapcsolattartó név", "Kapcsolattartó kategória ID", "Vevõ ID", "Pénzügyi képviselõ ID" ) AS
select
    contact.id                           as id,
    contact.name                         as "Kapcsolattartó név",
    contact.contactcategory_id           as "Kapcsolattartó kategória ID",
    contact.customer_basicpartner_id     as "Vevõ ID",
    contact.fiscalrepr_basicpartner_id   as "Pénzügyi képviselõ ID"
from
    contact 
;

CREATE OR REPLACE VIEW HU_VIEW_CONTACTCATEGORY ( id, Kategórianév ) AS
select
    contactcategory.id     as id,
    contactcategory.name   as "Kategórianév"
from
    contactcategory 
;

CREATE OR REPLACE VIEW HU_VIEW_CONTACTDATA ( id, "Közterület neve", "Közterületkategória ID", Házszám, Épület, Lépcsõház, Emelet, Ajtó, "Helyrajzi szám", Telefonszám, "E-mail", "Kapcsolattartó ID", "Ország ID", "Település ID", "Megye ID" ) AS
select
    contactdata.id                       as id,
    contactdata.puplicplacename          as "Közterület neve",
    contactdata.publicplacecategory_id   as "Közterületkategória ID",
    contactdata."number"                 as "Házszám",
    contactdata.building                 as "Épület",
    contactdata.staircase                as "Lépcsõház",
    contactdata.floorupstair             as "Emelet",
    contactdata.door                     as "Ajtó",
    contactdata.lotnumber                as "Helyrajzi szám ",
    contactdata.phonenumber              as "Telefonszám",
    contactdata."e-mail"                 as "E-mail",
    contactdata.contact_id               as "Kapcsolattartó ID",
    contactdata.country_id               as "Ország ID",
    contactdata.settlement_id            as "Település ID",
    contactdata.region_id			 as "Megye ID"
from
    contactdata 
;

CREATE OR REPLACE VIEW HU_VIEW_COUNTRY ( id, Országnév, "Ország kód" ) AS
select
    country.id            as id,
    country.name          as "Országnév",
    country.countrycode   as "Ország kód"
from
    country 
;

CREATE OR REPLACE VIEW HU_VIEW_CUSTOMER ( id, "Küldföldi adószám", "Adózási forma azonosító", Önadózó ) AS
select
    customer.basicpartner_id        as id,
    customer.thirdstatetaxid        as "Küldföldi adószám",
    customer.taxpayertype_id        as "Adózási forma azonosító",
    customer.selfbillingindicator   as "Önadózó"
from
    customer 
;

CREATE OR REPLACE VIEW HU_VIEW_CUSTOMERBANKACNUM ( id, Bankszámlaszám, "Bank ID", "Vevõ ID" ) AS
select
    customerbankacnum.id                         as id,
    customerbankacnum.bankaccountnumber          as "Bankszámlaszám",
    customerbankacnum.bank_id                    as "Bank ID",
    customerbankacnum.customer_basicpartner_id   as "Vevõ ID"
from
    customerbankacnum 
;

CREATE OR REPLACE VIEW HU_VIEW_ENTERPRISEDATA ( id, "Csoportos adószám", "Közösségi adószám" ) AS
select
    enterprisedata.basicpartner_id        as id,
    enterprisedata.groupmembertaxnumber   as "Csoportos adószám",
    enterprisedata.communityvatnumber     as "Közösségi adószám"
from
    enterprisedata 
;

CREATE OR REPLACE VIEW HU_VIEW_FISCALREPACNUM ( id, Bankszámlaszám, "Bank ID", "Pénzügyi képviselõ ID" ) AS
select
    fiscalrepbankacnum.id                           as id,
    fiscalrepbankacnum.bankaccountnumber            as "Bankszámlaszám",
    fiscalrepbankacnum.bank_id                      as "Bank ID",
    fiscalrepbankacnum.fiscalrepr_basicpartner_id   as "Pénzügyi képviselõ ID"
from
    fiscalrepbankacnum 
;

CREATE OR REPLACE VIEW HU_VIEW_FISCALREPREZENTATIVE ( "Partner ID" ) AS
select
    fiscalrepresentative.basicpartner_id as "Partner ID"
from
    fiscalrepresentative 
;

CREATE OR REPLACE VIEW HU_VIEW_INTERNALTAXNUMBER ( id, Adóazonosító, "ÁFA kód", Területkód ) AS
select
    internaltaxnumber.basicpartner_id   as id,
    internaltaxnumber.taxpayerid        as "Adóazonosító",
    internaltaxnumber.vatcode           as "ÁFA kód",
    internaltaxnumber.countycode        as "Területkód"
from
    internaltaxnumber 
;

CREATE OR REPLACE VIEW HU_VIEW_NAVUSER ( "Számlakiállító ID", "Bejelentkezési név", "Jelszó hash", Adószám, "Hívás aláírás" ) AS
select
    navuser.concern_id         as "Számlakiállító ID",
    navuser.login              as "Bejelentkezési név",
    navuser.passwordhash       as "Jelszó hash",
    navuser.taxnumber          as "Adószám",
    navuser.requestsignature   as "Hívás aláírás"
from
    navuser 
;

CREATE OR REPLACE VIEW HU_VIEW_PERSONDATAv1 ( id, "Születési idõ", "Ország ID", "Anyja neve", "Megye ID", "Település ID" ) AS
select
    persondata.basicpartner_id   as id,
    persondata.birthday          as "Születési idõ",
    persondata.country_id        as "Ország ID",
    persondata.nameofmothers     as "Anyja neve",
    persondata.region_id         as "Megye ID",
    persondata.settlement_id     as "Település ID"
from
    persondata 
;

CREATE OR REPLACE VIEW HU_VIEW_PUBLICPLACECATEGORY ( id, "Közterület megnevezése" ) AS
select
    publicplacecategory.id     as id,
    publicplacecategory.name   as "Közterület megnevezése"
from
    publicplacecategory 
;

CREATE OR REPLACE VIEW HU_VIEW_REGIONPLACE ( id, Megye, "Megye kód", "Ország ID" ) AS
select
    region.id           as id,
    region.name         as "Megye",
    region.regioncode   as "Megye kód",
    region.country_id   as "Ország ID"
from
    region 
;

CREATE OR REPLACE VIEW HU_VIEW_SETTLEMENT ( id, Településnév, Irányítószám, "Ország ID" ) AS
select
    settlement.id           as id,
    settlement.name         as "Településnév",
    settlement.postalcode   as "Irányítószám",
    settlement.country_id   as "Ország ID"
from
    settlement 
;

CREATE OR REPLACE VIEW HU_VIEW_TAXPAYERTYPE ( id, "Adózási forma", Leírás ) AS
select
    taxpayertype.id            as id,
    taxpayertype.name          as "Adózási forma",
    taxpayertype.description   as "Leírás"
from
    taxpayertype 
;

create sequence bank_id_seq start with 1 nocache order;

create or replace trigger bank_id_trg before
    insert on bank
    for each row
    when ( new.id is null )
begin
    :new.id := bank_id_seq.nextval;
end;
/

create sequence basicpartner_id_seq start with 1 nocache order;

create or replace trigger basicpartner_id_trg before
    insert on basicpartner
    for each row
    when ( new.id is null )
begin
    :new.id := basicpartner_id_seq.nextval;
end;
/

create sequence concernbankacnum_id_seq start with 1 nocache order;

create or replace trigger concernbankacnum_id_trg before
    insert on concernbankacnum
    for each row
    when ( new.id is null )
begin
    :new.id := concernbankacnum_id_seq.nextval;
end;
/

create sequence concernbankacnumtype_id_seq start with 1 nocache order;

create or replace trigger concernbankacnumtype_id_trg before
    insert on concernbankacnumtype
    for each row
    when ( new.id is null )
begin
    :new.id := concernbankacnumtype_id_seq.nextval;
end;
/

create sequence concerninvoiceblock_id_seq start with 1 nocache order;

create or replace trigger concerninvoiceblock_id_trg before
    insert on concerninvoiceblock
    for each row
    when ( new.id is null )
begin
    :new.id := concerninvoiceblock_id_seq.nextval;
end;
/

create sequence contact_id_seq start with 1 nocache order;

create or replace trigger contact_id_trg before
    insert on contact
    for each row
    when ( new.id is null )
begin
    :new.id := contact_id_seq.nextval;
end;
/

create sequence contactcategory_id_seq start with 1 nocache order;

create or replace trigger contactcategory_id_trg before
    insert on contactcategory
    for each row
    when ( new.id is null )
begin
    :new.id := contactcategory_id_seq.nextval;
end;
/

create sequence contactdata_id_seq start with 1 nocache order;

create or replace trigger contactdata_id_trg before
    insert on contactdata
    for each row
    when ( new.id is null )
begin
    :new.id := contactdata_id_seq.nextval;
end;
/

create sequence country_id_seq start with 1 nocache order;

create or replace trigger country_id_trg before
    insert on country
    for each row
    when ( new.id is null )
begin
    :new.id := country_id_seq.nextval;
end;
/

create sequence customerbankacnum_id_seq start with 1 nocache order;

create or replace trigger customerbankacnum_id_trg before
    insert on customerbankacnum
    for each row
    when ( new.id is null )
begin
    :new.id := customerbankacnum_id_seq.nextval;
end;
/

create sequence fiscalrepbankacnum_id_seq start with 1 nocache order;

create or replace trigger fiscalrepbankacnum_id_trg before
    insert on fiscalrepbankacnum
    for each row
    when ( new.id is null )
begin
    :new.id := fiscalrepbankacnum_id_seq.nextval;
end;
/

create sequence publicplacecategory_id_seq start with 1 nocache order;

create or replace trigger publicplacecategory_id_trg before
    insert on publicplacecategory
    for each row
    when ( new.id is null )
begin
    :new.id := publicplacecategory_id_seq.nextval;
end;
/

create sequence regionplace_id_seq start with 1 nocache order;

create or replace trigger regionplace_id_trg before
    insert on regionplace
    for each row
    when ( new.id is null )
begin
    :new.id := regionplace_id_seq.nextval;
end;
/

create sequence settlement_id_seq start with 1 nocache order;

create or replace trigger settlement_id_trg before
    insert on settlement
    for each row
    when ( new.id is null )
begin
    :new.id := settlement_id_seq.nextval;
end;
/

create sequence taxpayertype_id_seq start with 1 nocache order;

create or replace trigger taxpayertype_id_trg before
    insert on taxpayertype
    for each row
    when ( new.id is null )
begin
    :new.id := taxpayertype_id_seq.nextval;
end;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            56
-- CREATE INDEX                             5
-- ALTER TABLE                            145
-- CREATE VIEW                             22
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                          15
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                         15
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
